export const SCALES_CONFIG: Record<string, string> = {
  "C Major": "C D E F G A B",
  "G Major": "G A B C D E F#",
  "D Major": "D E F# G A B C#",
  "A Major": "A B C# D E F# G#",
  "E Major": "E F# G# A B C# D#",
  "B Major": "B C# D# E F# G# A#",
  "F# Major": "F# G# A# B C# D# E#",
  "Gb Major": "G# A# B C# D# E# F#",
  "Db Major": "Db Eb F Gb Ab Bb C",
  "Ab Major": "Ab Bb C Db Eb F G",
  "Eb Major": "Eb F G Ab Bb C D",
  "Bb Major": "Bb C D Eb F G A",
  "F Major": "F G A Bb C D E",
  "C# Major": "C# D# E# F# G# A# B#",

  "a minor": "A B C D E F G",
  "e minor": "E F# G A B C D",
  "b minor": "B C# D E F# G A",
  "f# minor": "F# G# A B C# D E",
  "c# minor": "C# D# E F# G# A B",
  "g# minor": "G# A# B C# D# E F#",
  "d# minor": "D# E# F# G# A# B C#",
  "eb minor": "E# F# G# A# B C# D#",
  "bb minor": "Bb C Db Eb F Gb Ab",
  "f minor": "F G Ab Bb C Db Eb",
  "c minor": "C D Eb F G Ab Bb",
  "g minor": "G A Bb C D Eb F",
  "d minor": "D E F G A Bb C",
};

export const DURATIONS = [
  ["w", "1/1"],
  ["h", "1/2"],
  ["q", "1/4"],
  ["8", "1/8"],
  ["16", "1/16"],
];
